export const BIBLE_BOOKS = [
  { abbrev: 'gn', name: 'Gênesis', author: 'Moisés', chapters: 50 },
  { abbrev: 'ex', name: 'Êxodo', author: 'Moisés', chapters: 40 },
  { abbrev: 'lv', name: 'Levítico', author: 'Moisés', chapters: 27 },
  { abbrev: 'nm', name: 'Números', author: 'Moisés', chapters: 36 },
  { abbrev: 'dt', name: 'Deuteronômio', author: 'Moisés', chapters: 34 },
  { abbrev: 'js', name: 'Josué', author: 'Josué', chapters: 24 },
  { abbrev: 'jz', name: 'Juízes', author: 'Samuel', chapters: 21 },
  { abbrev: 'rt', name: 'Rute', author: 'Samuel', chapters: 4 },
  { abbrev: '1sm', name: '1 Samuel', author: 'Samuel', chapters: 31 },
  { abbrev: '2sm', name: '2 Samuel', author: 'Samuel', chapters: 24 },
  { abbrev: '1rs', name: '1 Reis', author: 'Jeremias', chapters: 22 },
  { abbrev: '2rs', name: '2 Reis', author: 'Jeremias', chapters: 25 },
  { abbrev: '1cr', name: '1 Crônicas', author: 'Esdras', chapters: 29 },
  { abbrev: '2cr', name: '2 Crônicas', author: 'Esdras', chapters: 36 },
  { abbrev: 'ed', name: 'Esdras', author: 'Esdras', chapters: 10 },
  { abbrev: 'ne', name: 'Neemias', author: 'Neemias', chapters: 13 },
  { abbrev: 'et', name: 'Ester', author: 'Desconhecido', chapters: 10 },
  { abbrev: 'jo', name: 'Jó', author: 'Desconhecido', chapters: 42 },
  { abbrev: 'sl', name: 'Salmos', author: 'Vários', chapters: 150 },
  { abbrev: 'pv', name: 'Provérbios', author: 'Salomão', chapters: 31 },
  { abbrev: 'ec', name: 'Eclesiastes', author: 'Salomão', chapters: 12 },
  { abbrev: 'ct', name: 'Cânticos', author: 'Salomão', chapters: 8 },
  { abbrev: 'is', name: 'Isaías', author: 'Isaías', chapters: 66 },
  { abbrev: 'jr', name: 'Jeremias', author: 'Jeremias', chapters: 52 },
  { abbrev: 'lm', name: 'Lamentações', author: 'Jeremias', chapters: 5 },
  { abbrev: 'ez', name: 'Ezequiel', author: 'Ezequiel', chapters: 48 },
  { abbrev: 'dn', name: 'Daniel', author: 'Daniel', chapters: 12 },
  { abbrev: 'os', name: 'Oséias', author: 'Oséias', chapters: 14 },
  { abbrev: 'jl', name: 'Joel', author: 'Joel', chapters: 3 },
  { abbrev: 'am', name: 'Amós', author: 'Amós', chapters: 9 },
  { abbrev: 'ob', name: 'Obadias', author: 'Obadias', chapters: 1 },
  { abbrev: 'jn', name: 'Jonas', author: 'Jonas', chapters: 4 },
  { abbrev: 'mq', name: 'Miquéias', author: 'Miquéias', chapters: 7 },
  { abbrev: 'na', name: 'Naum', author: 'Naum', chapters: 3 },
  { abbrev: 'hc', name: 'Habacuque', author: 'Habacuque', chapters: 3 },
  { abbrev: 'sf', name: 'Sofonias', author: 'Sofonias', chapters: 3 },
  { abbrev: 'ag', name: 'Ageu', author: 'Ageu', chapters: 2 },
  { abbrev: 'zc', name: 'Zacarias', author: 'Zacarias', chapters: 14 },
  { abbrev: 'ml', name: 'Malaquias', author: 'Malaquias', chapters: 4 },
  { abbrev: 'mt', name: 'Mateus', author: 'Mateus', chapters: 28 },
  { abbrev: 'mc', name: 'Marcos', author: 'Marcos', chapters: 16 },
  { abbrev: 'lc', name: 'Lucas', author: 'Lucas', chapters: 24 },
  { abbrev: 'joao', name: 'João', author: 'João', chapters: 21 }, // keeping standard abbrev
  { abbrev: 'at', name: 'Atos', author: 'Lucas', chapters: 28 },
  { abbrev: 'rm', name: 'Romanos', author: 'Paulo', chapters: 16 },
  { abbrev: '1co', name: '1 Coríntios', author: 'Paulo', chapters: 16 },
  { abbrev: '2co', name: '2 Coríntios', author: 'Paulo', chapters: 13 },
  { abbrev: 'gl', name: 'Gálatas', author: 'Paulo', chapters: 6 },
  { abbrev: 'ef', name: 'Efésios', author: 'Paulo', chapters: 6 },
  { abbrev: 'fp', name: 'Filipenses', author: 'Paulo', chapters: 4 },
  { abbrev: 'cl', name: 'Colossenses', author: 'Paulo', chapters: 4 },
  { abbrev: '1ts', name: '1 Tessalonicenses', author: 'Paulo', chapters: 5 },
  { abbrev: '2ts', name: '2 Tessalonicenses', author: 'Paulo', chapters: 3 },
  { abbrev: '1tm', name: '1 Timóteo', author: 'Paulo', chapters: 6 },
  { abbrev: '2tm', name: '2 Timóteo', author: 'Paulo', chapters: 4 },
  { abbrev: 'tt', name: 'Tito', author: 'Paulo', chapters: 3 },
  { abbrev: 'fm', name: 'Filemom', author: 'Paulo', chapters: 1 },
  { abbrev: 'hb', name: 'Hebreus', author: 'Desconhecido', chapters: 13 },
  { abbrev: 'tg', name: 'Tiago', author: 'Tiago', chapters: 5 },
  { abbrev: '1pe', name: '1 Pedro', author: 'Pedro', chapters: 5 },
  { abbrev: '2pe', name: '2 Pedro', author: 'Pedro', chapters: 3 },
  { abbrev: '1jo', name: '1 João', author: 'João', chapters: 5 },
  { abbrev: '2jo', name: '2 João', author: 'João', chapters: 1 },
  { abbrev: '3jo', name: '3 João', author: 'João', chapters: 1 },
  { abbrev: 'jd', name: 'Judas', author: 'Judas', chapters: 1 },
  { abbrev: 'ap', name: 'Apocalipse', author: 'João', chapters: 22 }
];
